### ISSUE TITLE
Doesn't work on desktop

### ISSUE THREAD

**Issue by hrqmonteiro** [aaronraimist/element-themes#21]
I did everything as told in the readme, and the readme on "how to use a config.json file on desktop" and still doesn't work

So anyone help me, please.

**Comment by d2dyno** [comment]
I couldn't get it working either, so I just added the labs section from develop's example `config.json`, into Ubuntu's config directory `~/.config/Riot/config.json` :
```
{
	"features": {
	"feature_font_scaling": "labs",
	"feature_pinning": "labs",
	"feature_custom_status": "labs",
	"feature_custom_tags": "labs",
	"feature_state_counters": "labs",
	"feature_many_integration_managers": "labs",
	"feature_mjolnir": "labs",
	"feature_dm_verification": "labs",
	"feature_bridge_state": "labs",
	"feature_presence_in_room_list": "labs",
	"feature_custom_themes": "labs",
	"feature_new_room_list": "labs",
	"feature_irc_ui": "labs"
	}
}
```

**Comment by aaronraimist** [comment]
Apologies, I missed that this issue was open. I think what happened is that you just copied and pasted directly from the README which wasn't a complete `config.json` file. It was just showing one section of a `config.json` file. I have updated it now so it should be valid on it's own. Let me know if that solves your issue.
